
<h1>Prédire les cocnepts Rameau avec une base de vecteurs</h1>


* Pour chaque ligne de l'export, tu calcules le vecteur du titre-résumé. Rappel : une ligne peut posséder plusieurs vedettes rameau  (une vedette, c'est une zone 606, avec ou sans subdivision, cad avec un ou plusieurs ppn)
* Puis, pour chaque vedette rameau, tu agrèges les titres+résumés associés (GROUP BY), et tu fais la moyenne de leur vecteur (AGG(MEAN)
* Tu obtiens donc un vecteur par vedette rameau, qui "représente" toute la richesse contenue dans les titres et résumés des notices biblio ayant cette vedette. Appelons-ça ta grosse matrice Rameau++
* Ensuite, avec ce modèle, tu peux prédire les vedettes à associer à une nouvelle notice. Pour ce faire, tu vectorises le titre+résumé de la nouvelle notice et tu cherches le vecteur le plus proche de ta grosse matrice Rameau++

In [ ]:
#test d'extraction rameau a l'aide d'une base de vecteurs
import sys
!{sys.executable} -m pip install pinecone-client
!{sys.executable} -m  install sentence-transformers
!{sys.executable} -m  install datasets

In [1]:
import pandas as pd
import numpy as np
import simplemma
import nltk
from texthero import preprocessing as preprocessing2
import texthero as hero
import pickle


def lemmatize_text(text):
    w_tokenizer = nltk.tokenize.WhitespaceTokenizer()
    return ' '.join(word for word in [simplemma.lemmatize(w, lang='fr') for w in w_tokenizer.tokenize(text)])

2023-12-12 15:55:38.865264: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/srv/Annif/anaconda3/lib/python3.8/site-packages/spacy/util.py:910: UserWarning: [W095] Model 'en_core_web_sm' (3.2.0) was trained with spaCy v3.2.0 and may not be 100% compatible with the current version (3.6.1). If you see errors or degraded performance, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)

In [235]:
import pinecone

# connect to pinecone environment
pinecone.init(
    api_key="VOTRE_CLE_PINECONE",
    environment="us-west4-gcp"  # find next to API key in console
)

In [ ]:
if index_name in pinecone.list_indexes():
    pinecone.delete_index(index_name)

In [236]:
# pour re-indexer il faut au prealable supprimer l'index sur l'interface d'admin
index_name = 'extreme-ml'

# check if the extreme-ml index exists
if index_name not in pinecone.list_indexes():
    # create the index if it does not exist
    pinecone.create_index(
        index_name,
        dimension=384,
        
        metric="cosine"
    )

# connect to extreme-ml index we created
index = pinecone.Index(index_name)

In [ ]:
#chargemnt fichier d'entrainement

#df1 = pd.read_csv('export_picone.csv', sep='\t', skiprows=[12635,14570,20335,20655,32592,32975,32976,33310,50886,58789,58841,
#59676,63232,67341,72847,79427,80517,88343])
df1 = pd.read_csv('working_data_sans_dewey.csv', sep=',')

a = ['000308838','003632806','047450037','058296182','059911174','067313493','070072973','076503909','076986152','077463560','077880560','086077368','103220844','120997703','126056536','137422091','146527313','146979168','147294509','157175065','159761875','162374631','163093741','166049921','166278351','176553460','181543656','182508188','183201523','191351059','191415782','191552208','192576445','192816969','196109590','196122708','197101267','198384122','198388810','200050818','200404342','201602423','219465118','221455183','223827959','225697122','227065069','230373828','230756883','231055099','231860838','232821909','234544538','235109614','235130273','235280011','235755265','236616587','236660640','237131560','237156989','241152550','243051646','248194305','248590413','248915053','248944479','249549492','252457234','252816528','254162525','254992609','255264887','257349006','257504990','257936432','258740043','261199609','261643614','262267888','262760606','263439038','263487784','263926400','265476585','266197809','267884575','268799458','268924759','00094758X','05224170X','11707764X','18171681X','19580547X','23097368X','23690454X','24155859X','25561280X','26117309X','26753177X']
df1.info(verbose = False)
exclus=df1[df1['PPN'].isin(a)]
df1 = df1[~df1['PPN'].isin(a)]

df1.info(verbose = False)

mask = np.random.rand(len(df1)) < 0.81
training_data = df1[mask]
training_data.info(verbose = False)
training_data['PPN'].to_csv('data/training_data.csv',index=False)
testing_data = df1[~mask]
testing_data.info(verbose = False)
testing_data = testing_data.append(exclus, ignore_index=True)
testing_data.info(verbose = False)
testing_data['PPN'].to_csv('data/test_data.csv',index=False)
training_data["RESUME"] = training_data['TITRE'].astype(str) +", "+ training_data["RESUME"]
df=training_data.drop(columns=['PPN','TITRE','DEWEY'])

df['RAMEAU']=df['RAMEAU'].str.replace('_','#u#', regex=True).replace('"','#d#', regex=True).replace('\'','#c#', regex=True).replace(' ','_', regex=True)

#df.drop(index=df.index[89000:],axis=0, inplace=True)
#df.reset_index(drop=True, inplace=True)
#tronque
df['RESUME'] = df['RESUME'].str.slice(0,1000)

w_tokenizer = nltk.tokenize.WhitespaceTokenizer()
lemmatizer = nltk.stem.WordNetLemmatizer()
#lemmatization
df['RESUME'] = df['RESUME'].apply(lemmatize_text)

df.reset_index(drop=True, inplace=True)

In [257]:
testing_data.to_csv('testing_data_full.csv',index=False)

In [225]:

#NETTOYAGE
clean_pipeline = [preprocessing2.fillna,
                   preprocessing2.lowercase,
                   preprocessing2.remove_whitespace,
                   preprocessing2.remove_diacritics
                   
                  ]
df['RESUME'] = hero.clean(df['RESUME'], clean_pipeline)

df.head(5)

,CLE,RESUME,RAMEAU,DESCR,presence_chaine_indexation,rameau_chaines_index,rameau_concepts
0,0,"le culture pour vivre, mort de le culture popu...",Culture_populaire;Diffusion_de_la_culture;Poli...,La culture pour vivre Mort de la culture popul...,False,"['Culture populaire', 'Diffusion de la culture...","['Culture populaire', 'Diffusion de la culture..."
1,1,"le nuit, le jour : essai psychanalytique sur l...",Complexe_de_castration;Psychanalyse;Rêves,"La nuit, le jour : essai psychanalytique sur l...",False,"['Complexe de castration', 'Psychanalyse', 'Rê...","['Complexe de castration', 'Psychanalyse', 'Rê..."
2,2,"ruptures, cultures, il falloir imaginer robins...",Culture,"Ruptures, cultures Il faut imaginer Robinson s...",False,['Culture'],['Culture']
3,4,"le destruction de le temple, oswald tire sur k...",Science-fiction_américaine_--_Traductions_fran...,La Destruction du temple Oswald tire sur Kenne...,True,['Science-fiction américaine -- Traductions fr...,"['Science-fiction américaine', 'Traductions fr..."
4,5,"son pere jove, pelerin de l'image, naturalise ...",Photographie,"Mon père Jové, pèlerin de l'image Naturalisé f...",False,['Photographie'],['Photographie']

In [226]:

df['RAMEAU'] = df['RAMEAU'].str.split(';')
df.head(5)

,CLE,RESUME,RAMEAU,DESCR,presence_chaine_indexation,rameau_chaines_index,rameau_concepts
0,0,"le culture pour vivre, mort de le culture popu...","[Culture_populaire, Diffusion_de_la_culture, P...",La culture pour vivre Mort de la culture popul...,False,"['Culture populaire', 'Diffusion de la culture...","['Culture populaire', 'Diffusion de la culture..."
1,1,"le nuit, le jour : essai psychanalytique sur l...","[Complexe_de_castration, Psychanalyse, Rêves]","La nuit, le jour : essai psychanalytique sur l...",False,"['Complexe de castration', 'Psychanalyse', 'Rê...","['Complexe de castration', 'Psychanalyse', 'Rê..."
2,2,"ruptures, cultures, il falloir imaginer robins...",[Culture],"Ruptures, cultures Il faut imaginer Robinson s...",False,['Culture'],['Culture']
3,4,"le destruction de le temple, oswald tire sur k...",[Science-fiction_américaine_--_Traductions_fra...,La Destruction du temple Oswald tire sur Kenne...,True,['Science-fiction américaine -- Traductions fr...,"['Science-fiction américaine', 'Traductions fr..."
4,5,"son pere jove, pelerin de l'image, naturalise ...",[Photographie],"Mon père Jové, pèlerin de l'image Naturalisé f...",False,['Photographie'],['Photographie']

In [ ]:
#ne marche pas apres car type string suppression de ce qui suit -- 
#import re
#ch = '_--_'
#pattern  = ch + ".*"
#df["RAMEAU"] = df["RAMEAU"].apply(lambda x: re.sub(pattern, '', str(x) ))
#df.head(5)

In [264]:
#inutile
#creation jeux de test (les 460 derniers)
df_test=df.copy()
df_test.drop(index=df_test.index[:89000],axis=0, inplace=True)
df_test.reset_index(drop=True, inplace=True)
df_test
#print (len(df_test))

,RESUME,RAMEAU
0,"droit contemporain un pays arabes, souvent reg...",[Droit_islamique_--_Histoire]
1,"365 personnage qui avoir faire l'alsace, l'obj...",[Célébrités]
2,le guide de le trail : un premier foulee a les...,"[Course_en_montagne, Courses_à_pied, Raids_spo..."
3,"le savoir rural de le moyen age a son jours, l...","[Conditions_rurales_--_Histoire, Patrimoine_ru..."
4,"attentat de bassam : dans le feu de l'action, ...","[Terrorisme, Terrorisme_--_Politique_publique]"
...,...,...
411,le sentiment d'humanite : manifeste pour un fe...,"[Humanité, Réalisation_de_soi]"
412,"le saga un trois petit pois, trois pois, real,...","[Aliments_--_Ouvrages_pour_la_jeunesse, Pois_(..."
413,"droit de le representation de le personnel, pr...",[Représentation_du_personnel]
414,droit penal social : droit penal de le travail...,"[Droit_pénal, Sécurité_sociale_--_Droit_--_Dis..."
415,histoire de le college un medecin de le quebec...,"[Fraude_scientifique_--_Lutte_contre, Médecins..."

In [265]:
#inutile
#creation jeu de vectorization, les 89000 premiers
#suppression records de test
#index_list = list(range(9000, 9416))
#df.drop(df.index[index_list], inplace =True)
df.drop(index=df.index[89000:],axis=0, inplace=True)
df.reset_index(drop=True, inplace=True)
print (len(df))
df

89000

,RESUME,RAMEAU
0,"le culture pour vivre, mort de le culture popu...","[Culture_populaire, Diffusion_de_la_culture, P..."
1,"le nuit, le jour : essai psychanalytique sur l...","[Complexe_de_castration, Psychanalyse, Rêves]"
2,"ruptures, cultures, il falloir imaginer robins...",[Culture]
3,"le revolution structurale, mutation ou crises,...",[Structuralisme]
4,"le destruction de le temple, oswald tire sur k...",[Science-fiction_américaine_--_Traductions_fra...
...,...,...
88995,"le violence de l'etat, presentation un differe...","[Violence_policière, Violence_politique, État]"
88996,l'etat en france : entre deconstruction et rei...,"[Souveraineté, État, État_providence]"
88997,"le revolution militaire napoleonienne, apres a...","[Art_et_science_militaires, Art_et_science_mil..."
88998,franchise et partenariat : developper ou integ...,"[Alliances_stratégiques_(affaires), Concession..."
88999,le boite a outil de le e-commerce : 55 outil c...,"[Commerce_électronique, Marketing_sur_Internet]"

In [227]:
#chargement model
from sentence_transformers import SentenceTransformer
import torch

device = 'cuda' if torch.cuda.is_available() else 'cpu'

# load the model from huggingface
model = SentenceTransformer(
    'sentence-transformers/all-MiniLM-L6-v2',
    device=device
)
model

SentenceTransformer(
  (0): Transformer({'max_seq_length': 256, 'do_lower_case': False}) with Transformer model: BertModel
  (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False})
  (2): Normalize()
)

In [228]:
df

,CLE,RESUME,RAMEAU,DESCR,presence_chaine_indexation,rameau_chaines_index,rameau_concepts
0,0,"le culture pour vivre, mort de le culture popu...","[Culture_populaire, Diffusion_de_la_culture, P...",La culture pour vivre Mort de la culture popul...,False,"['Culture populaire', 'Diffusion de la culture...","['Culture populaire', 'Diffusion de la culture..."
1,1,"le nuit, le jour : essai psychanalytique sur l...","[Complexe_de_castration, Psychanalyse, Rêves]","La nuit, le jour : essai psychanalytique sur l...",False,"['Complexe de castration', 'Psychanalyse', 'Rê...","['Complexe de castration', 'Psychanalyse', 'Rê..."
2,2,"ruptures, cultures, il falloir imaginer robins...",[Culture],"Ruptures, cultures Il faut imaginer Robinson s...",False,['Culture'],['Culture']
3,4,"le destruction de le temple, oswald tire sur k...",[Science-fiction_américaine_--_Traductions_fra...,La Destruction du temple Oswald tire sur Kenne...,True,['Science-fiction américaine -- Traductions fr...,"['Science-fiction américaine', 'Traductions fr..."
4,5,"son pere jove, pelerin de l'image, naturalise ...",[Photographie],"Mon père Jové, pèlerin de l'image Naturalisé f...",False,['Photographie'],['Photographie']
...,...,...,...,...,...,...,...
125259,169658,blablabla : en finir avec le bavardage climati...,"[Réchauffement_de_la_Terre, Écologie]",Blablabla : en finir avec le bavardage climati...,False,"['Réchauffement de la Terre', 'Écologie']","['Réchauffement de la Terre', 'Écologie']"
125260,169659,politique de transition ecologique : democrati...,"[Aménagement_du_territoire, Marchés_publics, T...",Politique de transition écologique : Démocrati...,True,"['Aménagement du territoire', 'Marchés publics...","['Aménagement du territoire', 'Marchés publics..."
125261,169660,"abecedaire : mot et rite d'ailleurs, je dedier...","[Ethnopsychiatrie, Psychanalyse_et_ésotérisme,...",Abécédaire : mots et rites d'ailleurs Je dédie...,False,"['Ethnopsychiatrie', 'Psychanalyse et ésotéris...","['Ethnopsychiatrie', 'Psychanalyse et ésotéris..."
125262,169661,"consommer moins, consommer mieux, un cahier pr...","[Biens_de_consommation_durables, Consommation_...","Consommez moins, consommez mieux Un cahier pra...",True,"['Biens de consommation durables', 'Consommati...","['Biens de consommation durables', 'Consommati..."
125263,169662,le langage perdu un plante : avez-vous deja go...,"[Phytothérapie, Plantes_médicinales, Pollution...",Le langage perdu des plantes : avez-vous déjà ...,False,"['Phytothérapie', 'Plantes médicinales', 'Poll...","['Phytothérapie', 'Plantes médicinales', 'Poll..."

In [229]:
#creation des vecteurs
import pandas as pd

# Create embeddings
encoded_articles = model.encode(df['RESUME'].tolist(), show_progress_bar=True)
# add the embeddings to our dataframe
df['content_vector'] = pd.Series(encoded_articles.tolist())

Batches:   0%|          | 0/3915 [00:00<?, ?it/s]

In [230]:
#agregation
import numpy as np


df_explode = df.explode('RAMEAU')
#df_explode.head(5)

label_vectors = df_explode.groupby('RAMEAU').agg(mean=('content_vector', lambda x: np.vstack(x).mean(axis=0).tolist()))
label_vectors['target'] = label_vectors.index
label_vectors.columns = ['content_vector', 'label']

label_vectors.sample(10)

,content_vector,label
RAMEAU,,
Préfets_de_région,"[-0.06549372524023056, 0.03866653889417648, -0...",Préfets_de_région
Vitraux_--_Cathédrale_Notre-Dame,"[-0.0010548313148319721, 0.09218093007802963, ...",Vitraux_--_Cathédrale_Notre-Dame
Produits_de_luxe_--_Industrie_et_commerce,"[-0.023503052691618603, 0.051954121639331184, ...",Produits_de_luxe_--_Industrie_et_commerce
Éléments_(chimie)_--_Aspect_social,"[-0.08405434340238571, 0.08108076453208923, -0...",Éléments_(chimie)_--_Aspect_social
Gaspillage_des_finances_publiques,"[-0.08616872504353523, 0.03471718728542328, 0....",Gaspillage_des_finances_publiques
Assistance_médicalisée_pour_mourir_--_Aspect_religieux_--_Église_catholique,"[-0.0715772993862629, 0.10570614784955978, -0....",Assistance_médicalisée_pour_mourir_--_Aspect_r...
Responsabilité_(droit)_--_Histoire,"[-0.07808930426836014, 0.0645984634757042, -0....",Responsabilité_(droit)_--_Histoire
Capitalistes_et_financiers,"[-0.026554700220003724, 0.010577503100244535, ...",Capitalistes_et_financiers
Métaphore_--_Emploi_en_thérapeutique,"[0.023949647322297096, 0.06599561125040054, -0...",Métaphore_--_Emploi_en_thérapeutique
Caravagisme,"[-0.014488803688436747, 0.05620772670954466, -...",Caravagisme

In [263]:
label_vectors.head(100)

,content_vector,label
RAMEAU,,
#c#Ndrangheta,"[-0.0745735118786494, 0.03379224302868048, -0....",#c#Ndrangheta
"#c#Ūd,_Musique_d#c#_--_Histoire","[-0.004272089339792728, 0.10384338349103928, -...","#c#Ūd,_Musique_d#c#_--_Histoire"
#c#Ūd_--_Facture_(instruments_de_musique),"[-0.04093937948346138, -0.07384087890386581, -...",#c#Ūd_--_Facture_(instruments_de_musique)
#c#Ūd_--_Histoire,"[-0.004272089339792728, 0.10384338349103928, -...",#c#Ūd_--_Histoire
"10_et_11_janvier_2015,_Manifestations_des_(France)","[-0.030750181525945663, 0.04315360262989998, -...","10_et_11_janvier_2015,_Manifestations_des_(Fra..."
...,...,...
Abolitionnistes,"[-0.040964093059301376, 0.02886986406520009, -...",Abolitionnistes
Abolitionnistes_--_Histoire,"[-0.06544297188520432, 0.015964774414896965, 0...",Abolitionnistes_--_Histoire
Abondance_(économie_politique),"[-0.01768941804766655, -0.0038525641430169344,...",Abondance_(économie_politique)
Abordage_(droit_maritime),"[-0.04254164174199104, -0.004066053777933121, ...",Abordage_(droit_maritime)
Aborigènes_d#c#Australie,"[-0.015175560838542879, 0.07127911224961281, -...",Aborigènes_d#c#Australie

In [231]:
#sauvegarde des vecteur car long a produire
import pickle
label_vectors.to_pickle('cb_test_class_v2_vector_label.pkl') 
#label_vectors = pd.read_pickle('cb_test_class_v2_vector_label.pkl')

In [234]:
print(label_vectors.size)

125774

In [237]:
#alimentation index picone
from tqdm.auto import tqdm

# we will use batches of 256
batch_size = 256

for i in tqdm(range(0, len(label_vectors), batch_size)):
    # find end of batch
    i_end = min(i+batch_size, len(label_vectors))
    # extract batch
    batch = label_vectors.iloc[i:i_end]
    # select embeddings for batch
    emb = batch["content_vector"].tolist()
    # get metadata
    meta = [{"label": l} for l in batch["label"]]
    # create unique IDs
    ids = [f"{idx}" for idx in range(i, i_end)]
    # add all to upsert list
    to_upsert = list(zip(ids, emb, meta))
    # upsert/insert these records to pinecone
    _ = index.upsert(vectors=to_upsert)

  0%|          | 0/246 [00:00<?, ?it/s]

In [264]:
to_upsert

[('62720',
  [-0.0031574079766869545,
   -0.012853239042063555,
   0.027751542627811432,
   -0.07608327642083168,
   -0.0391421044866244,
   0.053137154007951416,
   -0.04282557281355063,
   0.08590315033992131,
   0.011098879699905714,
   0.015466515285273394,
   0.036108094888428845,
   -0.038559804670512676,
   0.03921550636490186,
   -0.04196954766909281,
   -0.04757632804103196,
   -0.07128716136018436,
   -0.03250103071331978,
   -0.04704896826297045,
   0.013209367791811625,
   0.03447853277126948,
   0.04114846015969912,
   -0.04945349941651026,
   0.024013972530762356,
   0.0108071972305576,
   0.0011015764127175014,
   -0.05028153335054716,
   0.004803851246833801,
   -0.021727894976114232,
   -0.02222566958516836,
   -0.022144639030254137,
   0.013772429122279087,
   0.029951420923074085,
   -0.0004725906377037366,
   0.010927237880726656,
   0.054731860756874084,
   -0.0016612131148576736,
   0.07650242000818253,
   0.002007116253177325,
   -0.0032632118090987206,
   0.09231745451688766,
   -0.023344213453431923,
   -0.0017661560947696369,
   -0.0725684550901254,
   -0.048104189025859036,
   0.0027030762430513278,
   -0.1039420614639918,
   0.04107389102379481,
   0.011478528380393982,
   -0.10711737970511119,
   -0.0037612166876594224,
   0.013310583929220835,
   0.0072390764447239535,
   0.012151383950064579,
   -0.03779886725048224,
   -0.061326598127683006,
   0.009864581593622765,
   -0.025807014976938564,
   -0.00871475568662087,
   0.008908985493083795,
   0.011761307095487913,
   -0.04425440231959025,
   -0.024887423147447407,
   0.013159743820627531,
   0.03649536023537318,
   -0.03968691639602184,
   -0.0017237622135629256,
   -0.010497802247603735,
   -0.028714044950902462,
   -0.0013174811999003093,
   0.011053350676471988,
   0.03161447743574778,
   -0.03968384303152561,
   -0.06519501407941182,
   0.005765265164275964,
   0.09189709772666295,
   0.024747250601649284,
   -0.07545572270949681,
   0.05223952792584896,
   -0.0178691732386748,
   -0.12646563847859701,
   0.079807015756766,
   -0.029536205033461254,
   -0.05415571853518486,
   -0.021655060350894928,
   0.03833885304629803,
   -0.05837360272804896,
   -0.009598734478155771,
   -0.008570982764164606,
   0.01008848256121079,
   -0.03876966051757336,
   0.027939160043994587,
   -0.03352692040304343,
   -0.08375328965485096,
   -0.004031426894168059,
   0.12764727075894675,
   0.01182096420476834,
   -0.014497114811092615,
   -0.0340332742780447,
   0.09913236647844315,
   0.017598488368093967,
   -0.00211456511169672,
   0.04519209669282039,
   0.007301909538606803,
   0.03178286459296942,
   -0.04272533332308134,
   -0.02639889034132163,
   0.013772721091906229,
   -0.04331295875211557,
   0.0029256734997034073,
   -0.025666438043117523,
   -0.03450313676148653,
   -0.02690150650839011,
   0.04428144753910601,
   0.005269666202366352,
   0.020569858762125175,
   -0.03612214761475722,
   0.016987875724832218,
   -0.06267145772775014,
   -0.0024913462499777475,
   -0.02455903682857752,
   0.004926389083266258,
   -0.01753221673425287,
   0.002802949088315169,
   -0.049726320430636406,
   0.041518806014209986,
   -0.004952612022558848,
   -0.028566353333493073,
   1.1420053983881237e-32,
   0.014080762513913214,
   0.05529920508464178,
   0.00086455171306928,
   -0.02377501440544923,
   -0.043347710743546486,
   0.04618099331855774,
   -0.07940717538197835,
   0.04890565139551958,
   0.05420998980601629,
   -0.07035002981623013,
   -0.0037830928534579775,
   0.10914850731690724,
   0.026054146389166515,
   0.007026389706879854,
   0.043511704464132585,
   0.009878825939570865,
   -0.00839470440405421,
   0.03706176392734051,
   -0.04741767964636286,
   0.02001479493143658,
   0.003545497078448534,
   0.0031517477085193,
   0.04786656672755877,
   0.04593934925893942,
   0.02735101788615187,
   0.01743832727273305,
   -0.0017750272527337074,
   -0.038748844216267266,
   -0.042238276451826096,
   0.018468643849094708,
   0.025022365463276703,
   -0.06274097040295601,
   -0.059938883098463215,
   -0.02291369885400248,
   -0.010150456180175146,
   -0.030917000335951645,
   0.06581609447797139,
   0.013262717674175898,
   0.05699630578358968,
   -0.017830562312155962,
   -0.030001697751382988,
   0.04893560707569122,
   0.04893700250734886,
   -0.01692726742476225,
   0.046922370636214815,
   0.0016319099813699722,
   0.02779635104040305,
   0.008408078499390589,
   0.08021659372995298,
   -0.027496205642819405,
   0.006961066431055467,
   -0.025405394999931257,
   -0.024136274742583435,
   -0.061965372413396835,
   0.017272673547267914,
   0.00010517751798033714,
   -0.07687197377284367,
   0.030763339018449187,
   -0.04566178129365047,
   -0.056147644917170204,
   0.05206632552047571,
   0.057329568080604076,
   -0.02471253485418856,
   -0.022718883585184813,
   0.012093303763928512,
   -0.023964162915945053,
   -0.07542427629232407,
   -0.0037766833362790444,
   0.11038543035586675,
   -0.028563753934577107,
   -0.06702813133597374,
   -0.021266366355121136,
   0.02193469988803069,
   -0.031361048420270286,
   0.04854206865032514,
   0.0547222209473451,
   -0.05759755025307337,
   0.02821154799312353,
   -0.019395935349166393,
   0.008545486256480217,
   -0.0424311396976312,
   -0.08323671917120616,
   -0.024082993467648823,
   -0.0491441508444647,
   0.005215908400714397,
   -0.028484813558558624,
   0.03281323549648126,
   0.024842610582709312,
   0.031475856356943645,
   -0.015647432766854763,
   0.06239113584160805,
   0.0067679496648149024,
   -0.0038679523083070913,
   0.046541640224556126,
   0.006643203708032767,
   -1.300080393046401e-32,
   0.0011489310612281163,
   0.009680229345879829,
   -0.04343970182041327,
   0.05888374956945578,
   0.04319543639818827,
   0.015500733007987341,
   0.02047463972121477,
   0.08689149220784505,
   -0.03611071780323982,
   -0.09381638715664546,
   0.003932241466827691,
   -0.067254938185215,
   0.08127251267433167,
   0.012724450478951136,
   -0.002351787406951189,
   0.07414095476269722,
   -0.03225326972703139,
   -0.025073337679107983,
   -0.048263837272922196,
   0.03308279253542423,
   0.06007826824982961,
   -0.06684426963329315,
   0.03439566493034363,
   -0.05519837637742361,
   0.044416483491659164,
   0.04438424917558829,
   -0.025780423544347286,
   -0.046617891639471054,
   -0.054813469449679054,
   -0.06358826657136281,
   -0.006657812123497327,
   0.0632402425010999,
   -0.03472814941778779,
   0.05785567810138067,
   0.004608815380682548,
   0.012881368631497025,
   0.06720702101786931,
   0.02162624305735032,
   -0.05790739258130392,
   0.09379687408606212,
   0.02585329208523035,
   0.04145484914382299,
   -0.011067607440054417,
   -0.027333607897162437,
   0.03928898833692074,
   0.010759700167303285,
   -0.035364995089670025,
   -0.021496328835686047,
   0.014058629826953014,
   -0.047972055772940315,
   -0.028405324866374333,
   0.026008474950989086,
   0.013761929702013731,
   -0.02039777860045433,
   0.02609493552396695,
   -0.001541552289078633,
   0.028223552120228607,
   -0.02476288191974163,
   -0.07377521445353825,
   0.028915047645568848,
   0.06109187689920267,
   0.06087148686250051,
   -0.039507380376259484,
   -0.013820331854124865,
   0.03185833579239746,
   -0.03559048225482305,
   -0.026638253902395565,
   0.006472434538106124,
   -0.06058250181376934,
   -0.015200303508512055,
   0.02978406473994255,
   -0.06789623573422432,
   -0.01119256035114328,
   -0.06483571231365204,
   -0.015873803446690243,
   0.07929571469624837,
   -0.006895829613010089,
   -0.05653245995442072,
   -0.06668950741489728,
   0.05099862813949585,
   -0.1920368323723475,
   -0.004882512924571832,
   -0.07015440861384074,
   -0.0037809014320373535,
   -0.03266778184721867,
   0.045865929375092186,
   -0.033627710615595184,
   -0.05354854743927717,
   0.03410908797134956,
   -0.03044661631186803,
   0.023308183765038848,
   -0.039995940091709294,
   0.029633996076881886,
   -0.05991127962867419,
   0.023557365716745455,
   -6.513534600571802e-08,
   -0.015558711485937238,
   -0.02761504923303922,
   -0.01930518029257655,
   0.050599850714206696,
   0.027523970153803628,
   -0.09759063025315602,
   -0.05382124831279119,
   0.008536907999465862,
   -0.038588693540077657,
   0.024633708720405895,
   -0.009667677028725544,
   -0.017590771274020273,
   -0.05090033325056235,
   -0.024404213453332584,
   0.027642484133442242,
   0.02860315392414729,
   0.03823492241402467,
   0.02631283427278201,
   -0.03621533140540123,
   -0.07713850152989228,
   0.05880519871910413,
   -0.03656917034337918,
   -0.053560110895584025,
   -0.0036810177067915597,
   -0.05734695175973078,
   0.029027730226516724,
   -0.037813919906814895,
   -0.0736946389079094,
   -0.05234616994857788,
   -0.0016354875018199284,
   -0.0212999212089926,
   0.03771748021245003,
   0.0038399191883703074,
   -0.10837240517139435,
   -0.009266321081668139,
   -0.020433881009618442,
   0.04442499577999115,
   0.04947289824485779,
   0.00553542748093605,
   -0.005617578038557743,
   0.07174703602989514,
   -0.0294983700538675,
   -0.012303370516747236,
   0.005817058030515909,
   0.10991102457046509,
   -0.050511037930846214,
   0.008319955629607042,
   0.04111705534160137,
   0.07574155926704407,
   0.012181697723766169,
   -0.05635445068279902,
   -0.011448959509531656,
   0.003942497540265322,
   -0.04899518874784311,
   -0.017457712441682816,
   0.029377245033780735,
   -0.004245756426826119,
   -0.030453340771297615,
   -0.052618736090759434,
   -0.03004527169590195,
   0.08083435893058777,
   0.06059686280786991,
   -0.02596339692051212,
   -0.0011333605895439784],
  {'label': 'Étudiants_de_première_année'}),
 ('62721',
  [-0.0022657925146631896,
   0.05015981639735401,
   -0.01229272736236453,
   -0.07283288985490799,
   -0.01039170939475298,
   -0.00745639210799709,
   0.0018538215663284063,
   0.03722260845825076,
   -0.0005334378220140934,
   0.02357118669897318,
   -0.016481361933983862,
   -0.062274995259940624,
   0.015259044710546732,
   -0.012131433933973312,
   -0.02729122480377555,
   -0.06862870045006275,
   0.011297649005427957,
   0.011685034456604626,
   0.022342915704939514,
   0.053834605030715466,
   -0.0005301679484546185,
   -0.042480760253965855,
   -0.02813542354851961,
   -0.0027583280025282875,
   -0.03463798575103283,
   -0.03517663152888417,
   -0.030192560167051852,
   -0.0024088553473120555,
   0.04504561092471704,
   -0.034875754034146667,
   0.05356025788933039,
   0.0448569399304688,
   -0.011334860362694599,
   -0.0033295571338385344,
   0.04294511419720948,
   0.07614975515753031,
   0.015977883085724898,
   -0.06622061133384705,
   -0.04772840952500701,
   0.04195368988439441,
   -0.056415855418890715,
   0.019282654859125614,
   -0.10921680927276611,
   -0.054298573173582554,
   0.010110004397574812,
   -0.005212767166085541,
   0.02984372031642124,
   0.021370680071413517,
   -0.1100121010094881,
   -0.038737175753340125,
   -0.010798151837661862,
   -0.0034125789534300566,
   0.013417193724308163,
   -0.01648667096742429,
   -0.05048864020500332,
   -0.01459492463618517,
   -0.0017624725587666035,
   -0.03899244777858257,
   -0.0005176733247935772,
   -0.04248423874378204,
   0.018969498807564378,
   0.012114417040720582,
   -0.02159026265144348,
   0.02011203661095351,
   -0.03231198946014047,
   -0.017116489121690392,
   -0.01149193849414587,
   0.029587058583274484,
   -0.018030762672424316,
   -0.022427606396377087,
   0.09030889444693457,
   -0.0831143818795681,
   0.009580750192981213,
   -0.05565321072936058,
   0.04799945093691349,
   0.033944247057661414,
   -0.053284892812371254,
   0.019277195911854506,
   -0.010257874499075115,
   -0.14913485199213028,
   0.09617378190159798,
   -0.028156409040093422,
   -0.017238550819456577,
   0.007327180239371955,
   -0.0030341746751219034,
   -0.04207572806626558,
   0.008722030092030764,
   0.004128676373511553,
   0.03215270070359111,
   -0.015441977826412767,
   0.0336467525921762,
   0.03696009167470038,
   -0.06284386198967695,
   0.015118850395083427,
   0.08462123479694128,
   0.01297275337856263,
   -0.04879944398999214,
   -0.061773995868861675,
   0.0434737044852227,
   0.050854706671088934,
   -0.04493212001398206,
   0.0037864838959649205,
   0.04001404356677085,
   5.363996024243534e-06,
   -0.06261325467494316,
   -0.049469294026494026,
   -0.021868514362722635,
   -0.0049733491614460945,
   -0.04793774662539363,
   0.02920100139454007,
   -0.07095428323373199,
   -0.02675458788871765,
   0.0012746208813041449,
   -0.003728597715962678,
   0.025101428196649067,
   -0.019860670901834965,
   -0.021047749556601048,
   -0.07886300142854452,
   0.03673161694314331,
   -0.043365742079913616,
   0.0656773429363966,
   0.0013976981572341174,
   -0.012270835926756263,
   -0.03244365914724767,
   0.011757827596738935,
   -0.03542352451768238,
   -0.007557672914117575,
   7.990317973577887e-33,
   -0.003798151621595025,
   0.02369908383116126,
   -0.030322057893499732,
   0.020594097208231688,
   0.058400257490575314,
   0.004277623840607703,
   -0.0028463072376325727,
   0.04220865899696946,
   0.012805652222596109,
   -0.019059065845794976,
   0.01553016947582364,
   0.05038769729435444,
   -0.007288492488441989,
   0.056956070475280285,
   0.07059273775666952,
   -0.056193290278315544,
   0.017300832085311413,
   0.04015580308623612,
   0.006625338923186064,
   -0.00935217080404982,
   -0.06154673267155886,
   0.031027680088300258,
   0.040635799523442984,
   0.025493363733403385,
   0.0435345524456352,
   0.016820532851852477,
   -0.014640148263424635,
   -0.060564772225916386,
   -0.08735301252454519,
   0.024490877985954285,
   0.03488849871791899,
   -0.018168268376030028,
   -0.014982359483838081,
   0.017691931687295437,
   -0.025657513993792236,
   -0.04428197583183646,
   0.013451945087581407,
   -0.00699638738296926,
   -0.015370262670330703,
   -0.031047997996211052,
   -0.004245868884027004,
   -0.0031788053502168623,
   0.02639525872655213,
   -0.006184917176142335,
   0.020561131183058023,
   0.024757870007306337,
   0.045119731687009335,
   -0.006945687171537429,
   0.027754181995987892,
   0.006079373182728887,
   0.02474585419986397,
   0.037115359969902784,
   -0.04221861071710009,
   -0.07201886922121048,
   0.03254396250122227,
   -0.028905797167681158,
   -0.06685156095772982,
   0.0030764258990529925,
   -0.03242104919627309,
   -0.06728829257190228,
   0.007225159715744667,
   0.014532596920616925,
   -0.024351077154278755,
   -0.005914694629609585,
   0.004991412133676931,
   -0.021532074257265776,
   -0.03086364417686127,
   0.028643475845456123,
   0.08330441452562809,
   -0.037440945859998465,
   -0.10641455836594105,
   0.0004750892985612154,
   0.03908114368095994,
   0.00020697317086160183,
   0.00709233817178756,
   0.0324782847892493,
   -0.05200914293527603,
   0.03916849847882986,
   -0.07200654363259673,
   0.01744183013215661,
   -0.07613063789904118,
   0.03184566448908299,
   -0.03214684140402824,
   0.017636024858802557,
   0.048775231000036,
   -0.014859589282423258,
   0.06282388791441917,
   0.05327260154444957,
   0.018633401254191995,
   0.027724819956347346,
   -0.0008984606247395277,
   -0.0007651248015463352,
   0.03263484896160662,
   0.011223470326513052,
   0.010714872274547815,
   -1.1451962410692323e-32,
   -0.013720340968575329,
   -0.008067912422120571,
   -0.07144731283187866,
   0.016242799872998148,
   0.017825230257585645,
   -0.007679514237679541,
   -0.06049827113747597,
   -0.013145523611456156,
   0.003970511723309755,
   -0.01823226921260357,
   -0.04725241439882666,
   -0.03417860995978117,
   0.0610349727794528,
   -0.020637243753299117,
   -0.07446718076243997,
   0.04261103319004178,
   -0.01123456610366702,
   -0.07027419516816735,
   -0.06215042993426323,
   -0.019901566905900836,
   0.0501112665515393,
   0.0023954245261847973,
   0.037859318079426885,
   -0.025381431682035327,
   -0.057740965858101845,
   0.030152813531458378,
   -0.015446077799424529,
   -0.015074696158990264,
   -0.02655606484040618,
   -0.008865883108228445,
   -0.02190947299823165,
   -0.005769860465079546,
   -0.0012236370530445129,
   0.05148003390058875,
   0.017060762736946344,
   0.026314246701076627,
   0.06448231404647231,
   0.007597476185765117,
   -0.05197003670036793,
   0.04153137875255197,
   0.025249268393963575,
   0.020721317909192294,
   0.015580053674057126,
   0.003256934229284525,
   0.04801390413194895,
   -0.03874750388786197,
   -0.06435227766633034,
   -0.10070834308862686,
   -0.03291846485808492,
   -0.059069388546049595,
   0.06463675852864981,
   0.04004732216708362,
   0.010166357969865203,
   -0.08663226058706641,
   0.055326281581074,
   -0.004122391575947404,
   0.026440979447215796,
   -0.048219019547104836,
   -0.017402864003088325,
   0.06644649151712656,
   0.09341464564204216,
   0.04814052674919367,
   -0.06825238559395075,
   0.024579548160545528,
   0.03831845847889781,
   -0.024589206332166214,
   -0.03834172897040844,
   0.005503730149939656,
   -0.05133324768394232,
   0.01698038587346673,
   0.02370944421272725,
   -0.010722956852987409,
   -0.06077059544622898,
   -0.007957192487083375,
   -0.017646450200118124,
   0.028572078270372003,
   0.024968893267214298,
   0.01748635247349739,
   -0.0018354253843426704,
   0.04901441792026162,
   -0.13855636306107044,
   -0.024998367473017424,
   -0.02711843838915229,
   -0.025052061770111322,
   0.03091623866930604,
   -0.03208248317241669,
   -0.04931402544025332,
   -0.06268547894433141,
   0.0317171512870118,
   -0.013081767596304417,
   0.03742134018102661,
   -0.014411537311389111,
   0.03360906569287181,
   0.005601968674454838,
   0.06723556574434042,
   -6.420910114712797e-08,
   0.006343433458823711,
   -0.019375953590497375,
   -0.02464594889897853,
   -0.021914104858296923,
   -0.011429362930357456,
   -0.13571851141750813,
   0.023150042165070772,
   0.015831677708774805,
   -0.028600705787539482,
   0.05051837442442775,
   0.0009317309904872673,
   -0.030351575231179595,
   -0.016800373909063637,
   0.038207246107049286,
   0.02875737613067031,
   -0.0012814242509193718,
   -0.003222955856472254,
   0.00013944227248430252,
   -0.06665688566863537,
   -0.08247132040560246,
   0.06994670466519892,
   -0.011229540454223752,
   -0.07148497452726588,
   -0.06814802251756191,
   -0.030647888779640198,
   -0.025382275693118572,
   -0.03274166793562472,
   -0.11080716457217932,
   -0.0378995796199888,
   0.026713931234553456,
   -0.009356943017337471,
   0.054762958316132426,
   0.02289110329002142,
   -0.061023418966215104,
   -0.0013912093127146363,
   -0.006943791260709986,
   0.04487266158685088,
   0.00514998147264123,
   -0.0232099664863199,
   -0.016213785856962204,
   0.068415398709476,
   -0.001284381840378046,
   -0.018026657518930733,
   -0.016219535820710007,
   0.09575859177857637,
   -0.002115751034580171,
   0.013097421498969197,
   0.05678347637876868,
   0.03780863666906953,
   0.06726779695600271,
   -0.040524378418922424,
   0.026298599783331156,
   0.02793471235781908,
   -0.005435215338366106,
   0.005698268098058179,
   -0.009792385797481984,
   0.0010954256867989898,
   0.010453992988914251,
   0.03612046712078154,
   -0.04312357463641092,
   0.05932951578870416,
   0.0681969877332449,
   -0.029168427921831608,
   -0.0006581345805898309],
  {'label': 'Étudiants_en_architecture'}),
 ('62722',
  [-0.019010349176824093,
   0.08854429237544537,
   -0.017467545345425606,
   -0.043124628253281116,
   0.02175039134453982,
   0.06056859903037548,
   0.03670416586101055,
   0.022463465575128794,
   0.04522627778351307,
   0.007698433473706245,
   0.022190448828041553,
   -0.018613785970956087,
   0.0111203552223742,
   -0.04230282182106748,
   -0.015161709859967232,
   -0.02275726606603712,
   0.01066090352833271,
   0.04539257287979126,
   0.016659151297062635,
   0.11187374964356422,
   0.030341343954205513,
   -0.020599711686372757,
   0.028852000599727035,
   -0.004889892414212227,

In [238]:
# check that we have all vectors in index
index.describe_index_stats()

{'dimension': 384,
 'index_fullness': 0.0,
 'namespaces': {'': {'vector_count': 62887}},
 'total_vector_count': 62887}

In [271]:
from pprint import pprint
def select_test_article(index):
    print("choisi un element du fichier de  test:")
    # select the article associated with index from test split
    article = df_test.iloc[index]
    # print test article data
    data = {"RESUME": article.RESUME[:1000],  "Original Labels": list(article.RAMEAU)}
    pprint(data)
    return article
def query_pinecone(article, top_k=3):
    print("predict rameau:")
    # Create embeddings for test articles
    xq = model.encode(article.RESUME).tolist()
    # query pinecone for labels
    results = index.query(xq, top_k=top_k, include_metadata=True)
    print(results)
    # select only the labels from result and print
    labels = [res["metadata"]["label"] for res in results.matches]
    pprint({"Predicted Labels": labels})

In [ ]:
#test sur le sixieme record du jeu de test
article = select_test_article(0)

In [ ]:
#interrogation db vectorized pour ce record
query_pinecone(article, top_k=10)

In [268]:
#generation fichier excel sur evaluation

#import pandas as pd
import numpy as np
import simplemma
import nltk
from texthero import preprocessing as preprocessing2
import texthero as hero
import pickle
import pandas as pd
import numpy as np




def lemmatize_text(text):
    w_tokenizer = nltk.tokenize.WhitespaceTokenizer()
    return ' '.join(word for word in [simplemma.lemmatize(w, lang='fr') for w in w_tokenizer.tokenize(text)])

import pinecone

# connect to pinecone environment
pinecone.init(
    api_key="VOTRE_CLE_PINECONE",
    environment="us-west4-gcp"  # find next to API key in console
)

def predict(text):
    xq = model.encode(lemmatize_text(text)).tolist()
    results = index.query(xq, top_k=10, include_metadata=True)
    return results

#chargement model
from sentence_transformers import SentenceTransformer
import torch

device = 'cuda' if torch.cuda.is_available() else 'cpu'

# load the model from huggingface
model = SentenceTransformer(
    'sentence-transformers/all-MiniLM-L6-v2',
    device=device
)

index = pinecone.Index('extreme-ml')
# faut jour les entetes et le connection a la base vecteurs
#df1 = pd.read_csv('export_picone_100.csv', sep='\t', skiprows=[12635,14570,20335,20655,32592,32975,32976,33310,50886,58789,58841,59676,63232,67341,72847,79427,80517,88343])
df1=testing_data.head(100).copy()
#df1=testing_data.copy()
df1["RESUME"] = df1['TITRE'].astype(str) +", "+ df1["RESUME"]
#-df=df1.drop(columns=['PPN','TITRE','DEWEY'])
df_test=df1
df_test['RAMEAU']=df_test['RAMEAU'].str.replace('_','#u#', regex=True).replace('"','#d#', regex=True).replace('\'','#c#', regex=True).replace(' ','_', regex=True)
#tronque
df_test['RESUME'] = df_test['RESUME'].str.slice(0,1000)
w_tokenizer = nltk.tokenize.WhitespaceTokenizer()
lemmatizer = nltk.stem.WordNetLemmatizer()
#lemmatization
df_test['RESUME'] = df_test['RESUME'].apply(lemmatize_text)
df_test['RAMEAU'] = df_test['RAMEAU'].str.split(';')
#df_test=df.copy()
#df_test.drop(index=df_test.index[:89200],axis=0, inplace=True)
#df_test.reset_index(drop=True, inplace=True)
#predictions
df_test['PREDICT'] = df_test['RESUME'].apply(predict)
#df_test['PREDICT'].head()
#df_test.to_csv('test_cbd.csv', sep='\t', encoding='utf-8')
df_test.to_csv('test_cbd_100_2.csv',index=False)
df_test

,CLE,PPN,TITRE,RESUME,RAMEAU,DEWEY,DESCR,presence_chaine_indexation,rameau_chaines_index,rameau_concepts,PREDICT
0,3,00002564X,La révolution structurale,"le révolution structurale, mutation ou crises,...",[Structuralisme],100,"La révolution structurale Mutations ou crises,...",False,['Structuralisme'],['Structuralisme'],"{'matches': [{'id': '29148', 'me..."
1,17,000057525,La théorie des jeux et ses applications à l'éc...,le théorie un jeu et son application à l'écono...,"[Mathématiques_économiques, Théorie_des_jeux]",519.3,La théorie des jeux et ses applications à l'éc...,False,"['Mathématiques économiques', 'Théorie des jeux']","['Mathématiques économiques', 'Théorie des jeux']","{'matches': [{'id': '34718', 'me..."
2,22,000079472,Pétrole : le vrai dossier,"pétrole : le vrai dossier, que dissimuler le é...",[Crise_économique_(1973)],320,Pétrole : le vrai dossier Que dissimulent les ...,False,['Crise économique (1973)'],['Crise économique (1973)'],"{'matches': [{'id': '46826', 'me..."
3,23,000085642,Magie : aspects de la tradition occidentale,"magie : aspect de le tradition occidentale, le...",[Magie],100,Magie : aspects de la tradition occidentale La...,False,['Magie'],['Magie'],"{'matches': [{'id': '33494', 'me..."
4,25,000087637,Mathématiques de base pour les linguistes,"mathématique de base pour le linguistes, le fo...","[Linguistique_--_Méthodes_graphiques, Linguist...",510,Mathématiques de base pour les linguistes La f...,True,"['Linguistique -- Méthodes graphiques', 'Lingu...","['Linguistique', 'Méthodes graphiques', 'Lingu...","{'matches': [{'id': '23295', 'me..."
...,...,...,...,...,...,...,...,...,...,...,...
95,479,001246259,Moïse géographe : recherches sur les représent...,moïse géographe : recherche sur le représentat...,"[Espace_--_Aspect_religieux_--_Christianisme, ...",200,Moïse géographe : recherches sur les représent...,True,['Espace -- Aspect religieux -- Christianisme'...,"['Espace', 'Aspect religieux', 'Christianisme'...","{'matches': [{'id': '25857', 'me..."
96,481,001249835,Former des enfants producteurs de textes,"former un enfant producteur de textes, groupe ...","[Créativité_(éducation), Français_(langue)_--_...",370,Former des enfants producteurs de textes Group...,True,"['Créativité (éducation)', 'Français (langue) ...","['Créativité (éducation)', 'Français (langue)'...","{'matches': [{'id': '23263', 'me..."
97,486,001263099,Multilinguisme et multiculturalisme en Amériqu...,multilinguisme et multiculturalisme en Amériqu...,"[Femmes_et_judaïsme, Littérature_et_société, L...",801,Multilinguisme et multiculturalisme en Amériqu...,False,"['Femmes et judaïsme', 'Littérature et société...","['Femmes et judaïsme', 'Littérature et société...","{'matches': [{'id': '32428', 'me..."
98,492,001278916,Aspects du mythe,"aspect de le mythe, le fonction de le mythe êt...","[Mythe, Mythologie_comparée, Société_primitive]",100,Aspects du mythe La fonction du mythe est de d...,False,"['Mythe', 'Mythologie comparée', 'Société prim...","['Mythe', 'Mythologie comparée', 'Société prim...","{'matches': [{'id': '37027', 'me..."
99,506,001300989,Visages de la littérature féminine,"visage de le littérature féminine, pendant un ...",[Littérature_belge_de_langue_française_--_Femm...,801,Visages de la littérature féminine Pendant des...,True,['Littérature belge de langue française -- Fem...,"['Littérature belge de langue française', 'Fem...","{'matches': [{'id': '21908', 'me..."

In [267]:
import json
import csv
import pandas
import ast

df_res=pd.DataFrame()

def extract_json(ppn,text):
    #text = ast.literal_eval(json.dumps(text))
    global df_res
    #print(text)
    x = json.loads(text)
    load_items = []
    
    for item in x["matches"]:
        #print(item["metadata"]["label"])
        load_items.append({'ppn': ppn,'score': item['score'],'label': item["metadata"]["label"]  })
            #load_items.append({'metadata': item2['label'] })
    z = pd.DataFrame(load_items)
    df_res=df_res.append(load_items, ignore_index=True)
    return z
df_test2 = df_test[['PPN', 'PREDICT']]
df_test2['PREDICT'] = df_test2['PREDICT'].astype(str).replace('\'', '"', regex=True).replace('\n', '', regex=True).replace('             ', ' ', regex=True)
#df_test2['PREDICT'] = df_test2['PREDICT'].astype(str).replace('""', '#db#', regex=True).replace('"', '#dc#', regex=True).replace('#db#', '\'', regex=True).replace('#dc#', '\'', regex=True).replace('\"', '#df#', regex=True).replace('\'', '"', regex=True).replace('\n', '', regex=True).replace('             ', ' ', regex=True)



df_test2.apply(lambda x: extract_json(x.PPN, x.PREDICT), axis=1)
df_res['label']=df_res['label'].replace('#u#','_', regex=True).replace('#d#','"', regex=True).replace('#c#','\'', regex=True).replace('_',' ', regex=True)
df_res.to_csv('test_cbd_100_3.csv',index=False)

/tmp/ipykernel_54440/1872417491.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test2['PREDICT'] = df_test2['PREDICT'].astype(str).replace('\'', '"', regex=True).replace('\n', '', regex=True).replace('             ', ' ', regex=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)

/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)

/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)
/tmp/ipykernel_54440/1872417491.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_res=df_res.append(load_items, ignore_index=True)

In [251]:
df_res.head()

         ppn     score                        label
0  00002564X  0.797656    Innovation_--_Philosophie
1  00002564X  0.779785  Innovation_--_Aspect_social
2  00002564X  0.776861   Technique_--_Aspect_social
3  00002564X  0.775053    Technique_et_civilisation
4  00002564X  0.774057      Prévision_technologique

In [14]:
# test sur une entree
# a jouer une fois
#import pandas as pd
import numpy as np
import simplemma
import nltk
from texthero import preprocessing as preprocessing2
import texthero as hero
import pickle



def lemmatize_text(text):
    w_tokenizer = nltk.tokenize.WhitespaceTokenizer()
    return ' '.join(word for word in [simplemma.lemmatize(w, lang='fr') for w in w_tokenizer.tokenize(text)])

import pinecone

# connect to pinecone environment
pinecone.init(
    api_key="VOTRE_CLE_PINECONE",
    environment="us-west4-gcp"  # find next to API key in console
)

def predict(text):
    xq = model.encode(lemmatize_text(text)).tolist()
    results = index.query(xq, top_k=100, include_metadata=True)
    return results

#chargement model
from sentence_transformers import SentenceTransformer
import torch

device = 'cuda' if torch.cuda.is_available() else 'cpu'

# load the model from huggingface
model = SentenceTransformer(
    'sentence-transformers/all-MiniLM-L6-v2',
    device=device
)

index = pinecone.Index('extreme-ml')

In [18]:

predict('le dessin être un voyage : carnet de jean Léonard, le dizaine de carnet de voyages, rempli à le gré un années, temoignent de l inlassable curiosité et de le gourmandise intellectuel avec  laquelles jean Léonard aura retenir le beauté de le monde à le  pointe de le crayon. pour qui être passionné par le dessin,  feuilleter ce centaine de page être un contentement sans égal. y   être fixé le ligne un paysage contemplés, le ombre un ruer  arpentées, le contour un architecture visitées. rempart   d Essaouira, grand muraille de Chine, jardin de le Daisen-In à  kyoto, temple de Karnak, Skyline de New-York, Palais un filateur à  Ahmedabad, ruiner de Mycènes, panthéon romain, bord de mer en  bretagne...')

{'matches': [{'id': '7129',
              'metadata': {'label': 'Carnets_de_croquis'},
              'score': 0.77722007,
              'values': []},
             {'id': '29883',
              'metadata': {'label': 'Monuments_historiques'},
              'score': 0.755565524,
              'values': []},
             {'id': '2943',
              'metadata': {'label': 'Architecture_--_Histoire'},
              'score': 0.750746,
              'values': []},
             {'id': '29860',
              'metadata': {'label': 'Monuments'},
              'score': 0.745746791,
              'values': []},
             {'id': '49352',
              'metadata': {'label': 'Voyage'},
              'score': 0.74461633,
              'values': []},
             {'id': '34030',
              'metadata': {'label': 'Patrimoine_urbain'},
              'score': 0.744391799,
              'values': []},
             {'id': '13152',
              'metadata': {'label': 'Dessin_--_Thèmes,_motifs'},
              'score': 0.743897319,
              'values': []},
             {'id': '48080',
              'metadata': {'label': 'Utopies_architecturales'},
              'score': 0.743879497,
              'values': []},
             {'id': '30554',
              'metadata': {'label': 'Musées_(constructions)'},
              'score': 0.742389262,
              'values': []},
             {'id': '14895',
              'metadata': {'label': 'Décoration_architecturale'},
              'score': 0.742181122,
              'values': []},
             {'id': '3050',
              'metadata': {'label': 'Architecture_et_arts'},
              'score': 0.740345418,
              'values': []},
             {'id': '2906',
              'metadata': {'label': 'Architecture'},
              'score': 0.73940587,
              'values': []},
             {'id': '47283',
              'metadata': {'label': "Travaux_artistiques_d'étudiants"},
              'score': 0.739150763,
              'values': []},
             {'id': '31254',
              'metadata': {'label': 'Mégalithes_--_Ouvrages_illustrés'},
              'score': 0.737988591,
              'values': []},
             {'id': '51170',
              'metadata': {'label': 'Églises'},
              'score': 0.736069858,
              'values': []},
             {'id': '40929',
              'metadata': {'label': 'Ruines'},
              'score': 0.733805299,
              'values': []},
             {'id': '43328',
              'metadata': {'label': 'Sites_historiques'},
              'score': 0.733336687,
              'values': []},
             {'id': '32418',
              'metadata': {'label': 'Objets_religieux'},
              'score': 0.732055366,
              'values': []},
             {'id': '3061',
              'metadata': {'label': 'Architecture_et_littérature'},
              'score': 0.732025,
              'values': []},
             {'id': '10547',
              'metadata': {'label': 'Construction_--_Histoire'},
              'score': 0.731310308,
              'values': []},
             {'id': '29875',
              'metadata': {'label': 'Monuments_funéraires'},
              'score': 0.730090082,
              'values': []},
             {'id': '3137',
              'metadata': {'label': 'Architecture_religieuse'},
              'score': 0.729939818,
              'values': []},
             {'id': '35252',
              'metadata': {'label': "Photographie_d'architecture"},
              'score': 0.729176,
              'values': []},
             {'id': '2382',
              'metadata': {'label': 'Antiquités'},
              'score': 0.728336,
              'values': []},
             {'id': '49413',
              'metadata': {'label': 'Voyages_imaginaires'},
              'score': 0.727808237,
              'values': []},
             {'id': '49365',
              'metadata': {'label': 'Voyages'},
              'score': 0.727698088,
              'values': []},
             {'id': '3566',
              'metadata': {'label': 'Art_chrétien'},
              'score': 0.727529228,
              'values': []},
             {'id': '34123',
              'metadata': {'label': 'Paysage_urbain'},
              'score': 0.727141,
              'values': []},
             {'id': '49356',
              'metadata': {'label': 'Voyage_--_Dans_la_littérature'},
              'score': 0.725591958,
              'values': []},
             {'id': '41572',
              'metadata': {'label': "Résidences_d'artistes"},
              'score': 0.724832535,
              'values': []},
             {'id': '24389',
              'metadata': {'label': 'Installations_(art)'},
              'score': 0.724674404,
              'values': []},
             {'id': '3495',
              'metadata': {'label': 'Art_--_Thèmes,_motifs'},
              'score': 0.723910511,
              'values': []},
             {'id': '39391',
              'metadata': {'label': 'Reconversion_(architecture)'},
              'score': 0.723693,
              'values': []},
             {'id': '12649',
              'metadata': {'label': 'Curiosités_et_merveilles'},
              'score': 0.723592579,
              'values': []},
             {'id': '22299',
              'metadata': {'label': 'Histoire_locale'},
              'score': 0.72358197,
              'values': []},
             {'id': '47954',
              'metadata': {'label': 'Urbanisme_--_Histoire'},
              'score': 0.722791195,
              'values': []},
             {'id': '29863',
              'metadata': {'label': 'Monuments_--_Histoire'},
              'score': 0.722586632,
              'values': []},
             {'id': '2881',
              'metadata': {'label': 'Architectes'},
              'score': 0.720592141,
              'values': []},
             {'id': '2988',
              'metadata': {'label': 'Architecture_antique'},
              'score': 0.720226645,
              'values': []},
             {'id': '3149',
              'metadata': {'label': 'Architecture_vernaculaire'},
              'score': 0.719323575,
              'values': []},
             {'id': '2931',
              'metadata': {'label': 'Architecture_--_Dessins_et_plans'},
              'score': 0.718893886,
              'values': []},
             {'id': '49388',
              'metadata': {'label': 'Voyages_autour_du_monde'},
              'score': 0.717422187,
              'values': []},
             {'id': '3550',
              'metadata': {'label': 'Art_brut'},
              'score': 0.717077494,
              'values': []},
             {'id': '42584',
              'metadata': {'label': 'Sculpture'},
              'score': 0.717004895,
              'values': []},
             {'id': '29613',
              'metadata': {'label': 'Moeurs_et_coutumes'},
              'score': 0.716988325,
              'values': []},
             {'id': '48464',
              'metadata': {'label': 'Vie_artistique'},
              'score': 0.716760397,
              'values': []},
             {'id': '3405',
              'metadata': {'label': 'Art'},
              'score': 0.716591239,
              'values': []},
             {'id': '34274',
              'metadata': {'label': 'Peinture_et_décoration_murales'},
              'score': 0.716300845,
              'values': []},
             {'id': '3060',
              'metadata': {'label': 'Architecture_et_histoire'},
              'score': 0.716256142,
              'values': []},
             {'id': '51175',
              'metadata': {'label': 'Églises_--_Histoire'},
              'score': 0.71583271,
              'values': []},
             {'id': '33973',
              'metadata': {'label': 'Patrimoine_culturel'},
              'score': 0.715689898,
              'values': []},
             {'id': '3000',
              'metadata': {'label': 'Architecture_chrétienne'},
              'score': 0.71477288,
              'values': []},
             {'id': '3100',
              'metadata': {'label': 'Architecture_littorale'},
              'score': 0.714208424,
              'values': []},
             {'id': '4125',
              'metadata': {'label': 'Arts_décoratifs'},
              'score': 0.714010477,
              'values': []},
             {'id': '14940',
              'metadata': {'label': 'Découverte_et_exploration'},
              'score': 0.713715196,
              'values': []},
             {'id': '34166',
              'metadata': {'label': 'Peintres'},
              'score': 0.713563919,
              'values': []},
             {'id': '3039',
              'metadata': {'label': 'Architecture_du_paysage'},
              'score': 0.713281572,
              'values': []},
             {'id': '3951',
              'metadata': {'label': 'Artisans'},
              'score': 0.712886155,
              'values': []},
             {'id': '41077',
              'metadata': {'label': "Réalisations_d'élèves"},
              'score': 0.712858796,
              'values': []},
             {'id': '3957',
              'metadata': {'label': 'Artistes'},
              'score': 0.712831557,
              'values': []},
             {'id': '21704',
              'metadata': {'label': 'Géométrie_--_Ouvrages_de_vulgarisation'},
              'score': 0.712239861,
              'values': []},
             {'id': '48748',
              'metadata': {'label': 'Villes_--_Dans_la_littérature'},
              'score': 0.712131679,
              'values': []},
             {'id': '3882',
              'metadata': {'label': 'Art_urbain'},
              'score': 0.710764468,
              'values': []},
             {'id': '40893',
              'metadata': {'label': 'Rues'},
              'score': 0.710263848,
              'values': []},
             {'id': '3141',
              'metadata': {'label': 'Architecture_romaine'},
              'score': 0.70967,
              'values': []},
             {'id': '19064',
              'metadata': {'label': 'Fouilles_archéologiques'},
              'score': 0.709607363,
              'values': []},
             {'id': '34238',
              'metadata': {'label': 'Peinture_--_Thèmes,_motifs'},
              'score': 0.708564341,
              'values': []},
             {'id': '26151',
              'metadata': {'label': 'Land_art'},
              'score': 0.707822084,
              'values': []},
             {'id': '3746',
              'metadata': {'label': 'Art_in_situ'},
              'score': 0.707313776,
              'values': []},
             {'id': '3857',
              'metadata': {'label': 'Art_public'},
              'score': 0.70728904,
              'values': []},
             {'id': '3663',
              'metadata': {'label': 'Art_déco'},
              'score': 0.706986785,
              'values': []},
             {'id': '29640',
              'metadata': {'label': 'Moeurs_et_coutumes_--_Photographies'},
              'score': 0.706779122,
              'values': []},
             {'id': '49425',
              'metadata': {'label': 'Voyageurs'},
              'score': 0.706594169,
              'values': []},
             {'id': '30687',
              'metadata': {'label': 'Mythes_géographiques'},
              'score': 0.706361294,
              'values': []},
             {'id': '48796',
              'metadata': {'label': 'Villes_disparues,_en_ruine,_etc.'},
              'score': 0.706305444,
              'values': []},
             {'id': '23240',
              'metadata': {'label': 'Illustration_archéologique'},
              'score': 0.706225574,
              'values': []},
             {'id': '29874',
              'metadata': {'label': 'Monuments_disparus_--_Ouvrages_illustrés'},
              'score': 0.706225574,
              'values': []},
             {'id': '34197',
              'metadata': {'label': 'Peinture'},
              'score': 0.705943048,
              'values': []},
             {'id': '7149',
              'metadata': {'label': "Carrières_(sites_d'extraction)"},
              'score': 0.705684066,
              'values': []},
             {'id': '37782',
              'metadata': {'label': "Projets_d'architecture"},
              'score': 0.705405295,
              'values': []},
             {'id': '3145',
              'metadata': {'label': 'Architecture_romane'},
              'score': 0.705291212,
              'values': []},
             {'id': '42581',
              'metadata': {'label': 'Sculpteurs'},
              'score': 0.704921901,
              'values': []},
             {'id': '14902',
              'metadata': {'label': 'Décoration_intérieure'},
              'score': 0.704429448,
              'values': []},
             {'id': '30168',
              'metadata': {'label': 'Mouvement_moderne_(architecture)'},
              'score': 0.704355776,
              'values': []},
             {'id': '23234',
              'metadata': {'label': 'Illustrateurs'},
              'score': 0.703889966,
              'values': []},
             {'id': '42628',
              'metadata': {'label': 'Sculpture_en_pierre'},
              'score': 0.703628719,
              'values': []},
             {'id': '3664',
              'metadata': {'label': 'Art_déco_(architecture)'},
              'score': 0.702952445,
              'values': []},
             {'id': '26733',
              'metadata': {'label': 'Lieux_imaginaires_--_Dans_la_littérature'},
              'score': 0.702685177,
              'values': []},
             {'id': '2451',
              'metadata': {'label': 'Antiquités_romaines'},
              'score': 0.702650666,
              'values': []},
             {'id': '21794',
              'metadata': {'label': 'Habitations'},
              'score': 0.702413,
              'values': []},
             {'id': '4048',
              'metadata': {'label': 'Arts'},
              'score': 0.701891,
              'values': []},
             {'id': '37810',
              'metadata': {'label': 'Promenade'},
              'score': 0.701342344,
              'values': []},
             {'id': '13185',
              'metadata': {'label': 'Dessinateurs_de_bandes_dessinées'},
              'score': 0.70079267,
              'values': []},
             {'id': '40899',
              'metadata': {'label': 'Rues_--_Histoire_--_Dictionnaires'},
              'score': 0.700789452,
              'values': []},
             {'id': '46605',
              'metadata': {'label': 'Tourisme'},
              'score': 0.700104058,
              'values': []},
             {'id': '9212',
              'metadata': {'label': 'Collage_(art)'},
              'score': 0.700074852,
              'values': []},
             {'id': '48757',
              'metadata': {'label': 'Villes_--_Histoire'},
              'score': 0.699168742,
              'values': []},
             {'id': '3087',
              'metadata': {'label': 'Architecture_intérieure'},
              'score': 0.698888302,
              'values': []},
             {'id': '3875',
              'metadata': {'label': 'Art_textile'},
              'score': 0.698794365,
              'values': []},
             {'id': '40898',
              'metadata': {'label': 'Rues_--_Histoire'},
              'score': 0.698512852,
              'values': []},
             {'id': '16180',
              'metadata': {'label': 'Enluminure'},
              'score': 0.698232,
              'values': []},
             {'id': '26732',
              'metadata': {'label': 'Lieux_imaginaires'},
              'score': 0.698140264,
              'values': []},
             {'id': '17450',
              'metadata': {'label': "Exotisme_--_Dans_l'art"},
              'score': 0.697896361,
              'values': []},
             {'id': '7955',
              'metadata': {'label': "Chefs-d'oeuvre_(art)_--_Ouvrages_pour_la_jeunesse"},
              'score': 0.69787097,
              'values': []},
             {'id': '12955',
              'metadata': {'label': 'Danse_contemporaine'},
              'score': 0.697844803,
              'values': []},
             {'id': '23244',
              'metadata': {'label': 'Illustration_des_livres'},
              'score': 0.697743535,
              'values': []},
             {'id': '34094',
              'metadata': {'label': 'Paysage'},
              'score': 0.697514057,
              'values': []},
             {'id': '38633',
              'metadata': {'label': 'Pèlerinages'},
              'score': 0.697431684,
              'values': []},
             {'id': '29880',
              'metadata': {'label': 'Monuments_funéraires_antiques'},
              'score': 0.697256446,
              'values': []},
             {'id': '2907',
              'metadata': {'label': 'Architecture-sculpture'},
              'score': 0.697155893,
              'values': []},
             {'id': '17041',
              'metadata': {'label': 'Espaces_publics_--_Histoire'},
              'score': 0.697137,
              'values': []},
             {'id': '26736',
              'metadata': {'label': 'Lieux_sacrés'},
              'score': 0.697059572,
              'values': []},
             {'id': '46613',
              'metadata': {'label': 'Tourisme_--_Dans_la_littérature'},
              'score': 0.696524501,
              'values': []},
             {'id': '46634',
              'metadata': {'label': 'Tourisme_et_cinéma'},
              'score': 0.696491599,
              'values': []},
             {'id': '42675',
              'metadata': {'label': 'Scénaristes_de_bandes_dessinées'},
              'score': 0.696206689,
              'values': []},
             {'id': '43318',
              'metadata': {'label': 'Sites_archéologiques'},
              'score': 0.69612056,
              'values': []},
             {'id': '31697',
              'metadata': {'label': 'Nature_(esthétique)'},
              'score': 0.696053326,
              'values': []},
             {'id': '8339',
              'metadata': {'label': 'Chorégraphie'},
              'score': 0.695834637,
              'values': []},
             {'id': '26985',
              'metadata': {'label': 'Littérature_et_géographie'},
              'score': 0.695290208,
              'values': []},
             {'id': '3226',
              'metadata': {'label': 'Archéologie_et_histoire'},
              'score': 0.695253849,
              'values': []},
             {'id': '3601',
              'metadata': {'label': 'Art_dans_la_rue'},
              'score': 0.694880307,
              'values': []},
             {'id': '39182',
              'metadata': {'label': 'Randonnée_pédestre'},
              'score': 0.694858,
              'values': []},
             {'id': '29888',
              'metadata': {'label': 'Monuments_historiques_--_Histoire'},
              'score': 0.694823444,
              'values': []},
             {'id': '23378',
              'metadata': {'label': "Immeubles_d'habitation"},
              'score': 0.694306135,
              'values': []},
             {'id': '3676',
              'metadata': {'label': 'Art_et_danse'},
              'score': 0.694064379,
              'values': []},
             {'id': '2926',
              'metadata': {'label': 'Architecture_--_Conservation_et_restauration_--_Histoire'},
              'score': 0.693755507,
              'values': []},
             {'id': '23239',
              'metadata': {'label': 'Illustrateurs_pour_la_jeunesse'},
              'score': 0.692781746,
              'values': []},
             {'id': '3999',
              'metadata': {'label': 'Artistes_--_Voyages'},
              'score': 0.692556,
              'values': []},
             {'id': '7949',
              'metadata': {'label': "Chefs-d'oeuvre_(art)"},
              'score': 0.692104816,
              'values': []},
             {'id': '42002',
              'metadata': {'label': 'Sanctuaires'},
              'score': 0.692102611,